name: fireutil
description: Utility to manage Firestore databases.
version: 1.0.0
homepage: https://github.com/cachapa/fireutil
author: Daniel Cachapa <cachapa@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  firedart: ^0.5.1
